name: bdface's custom vib image
id: bdf-custom-vib
vibversion: 1.0.0

stages:
- id: build
  base: ghcr.io/vanilla-os/desktop:main # Optionally, Replace this image URL with a different one i.e. nvidia:main, etc
  addincludes: true
  singlelayer: false
  labels:
    maintainer: badlydrawnface
  args:
    DEBIAN_FRONTEND: noninteractive # Set the image environment as non-interactive

  # Commands to run first before building the modules
  runs:
    commands:
      - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends

  modules:
  - name: init-setup
    type: shell
    commands:
    - lpkg --unlock
    - apt-get update

  # Put your custom actions below this comment

  - name: install-util-packages
    type: apt
    sources:
      - packages:
        - neovim
        - lazygit
        - fastfetch
        - eza
        - fzf
        - bat
        - ripgrep
        - zoxide
        - delta
        - fd-find
        - btop

  # - name: install-ghostty
  #   type: shell
  #   commands:
  #   - curl -sS https://debian.griffo.io/EA0F721D231FDD3A0A17B9AC7808B4DD62C41256.asc | gpg --dearmor --yes -o /etc/apt/trusted.gpg.d/debian.griffo.io.gpg
  #   - echo "deb https://debian.griffo.io/apt/dists/sid/main" | tee /etc/apt/sources.list.d/debian.griffo.io.list
  #   - apt update && apt install -y ghostty

  - name: install-gaming-packages
    type: apt
    sources:
      - packages:
        - steam
        - lutris
        - mangohud
        - gamescope
        - protontricks

  - name: example-modules # Sample module demonstrating importing local and remote modules
    type: includes
    includes: 
      - modules/50-install-debs.yml # Sample local module present in this repository
      # - gh:vanilla-os/dev-image:main:modules/00-basics.yml # Sample GitHub remote module in the format: `gh:your-name/your-repo:branch:modules/file.yml`
      # - https://raw.githubusercontent.com/Vanilla-OS/dev-image/main/modules/05-go.yml # Sample full URL remote module

  # Put your custom actions above this comment

  - name: set-image-name-abroot
    type: includes
    includes:
      - modules/80-set-image-abroot-config.yml

  - name: cleanup
    type: shell
    commands:
    - apt-get autoremove -y
    - apt-get clean
    - lpkg --lock

  - name: fsguard
    type: fsguard
    CustomFsGuard: false
    FsGuardLocation: "/usr/sbin/FsGuard"
    GenerateKey: true
    FilelistPaths: ["/usr/bin"]
    modules:
      - name: remove-prev-fsguard
        type: shell
        commands:
          - rm -rf /FsGuard 
          - rm -f ./minisign.pub ./minisign.key 
          - chmod +x /usr/sbin/init

  - name: cleanup2
    type: shell
    commands:
      - rm -rf /tmp/*
      - rm -rf /var/tmp/*
